### ISSUE TITLE
F5 Issue

### ISSUE THREAD

**Issue by sample4u** [RiseVision/rise-react-wallet#223] opened 2019-04-12 11:01 UTC
When click f5 in wallet for refresh result is empty page with:

This site can’t be reached domain’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by TobiaszCudnik** [comment] 2019-04-15 15:45
Duplicate of https://github.com/RiseVision/rise-react-wallet/issues/161.

Workaround is to not use F5/refresh on the desktop wallet, as it refreshes itself automatically once connected (see the top right connection status icon).

**Closed by TobiaszCudnik** 2019-04-15 15:45 UTC
