### ISSUE TITLE
Update informations through WebSocket

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-react-wallet#126] opened 2018-11-06 08:59 UTC
Hello guys,

I've been testing the wallet and discovered that when broadcasting a transaction (or receiving a new one), data is not automatically updated unless I hit the F5 button.

We can leverage websockets for this purpose. We've "channels" for the following events happening in the node: 
![image](https://user-images.githubusercontent.com/200523/48053202-5dd91d80-e1aa-11e8-9afd-0e905d6d7785.png)

In case of the wallet we might need to implement:
 - `blocks/change` that will be broadcasted just after a block has been successfully applied
 - `rounds/change` that will be broadcasted at every round end (Delegate rankings might change)
 - `transactions/change` will be broadcasted every time a tx has been validated and goes into an unconfirmed state

**NOTE**: The transactions/change event might not be broadcasted at all for a transaction that was not known to the underlying node before being included in a block.

**Comment by roosmaa** [comment] 2018-11-06 09:28
Duplicate of #13 - closing this and mirroring the post in the original issue.

**Closed by roosmaa** 2018-11-06 09:28 UTC
Labels: enhancement
